replicaCount: 1

image:
  repository: demo-service
  tag: "dev"
  pullPolicy: IfNotPresent

service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

health:
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10

ingress:
  enabled: false

autoscaling:
  enabled: false

networkPolicy:
  enabled: true

serviceAccount:
  create: true