apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "platform-application.fullname" . }}
  labels:
    {{- include "platform-application.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "platform-application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "platform-application.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "platform-application.serviceAccountName" . }}
      
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault

          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          readinessProbe:
            httpGet:
              path: {{ .Values.health.path }}
              port: http
            initialDelaySeconds: {{ .Values.health.initialDelaySeconds }}
            periodSeconds: {{ .Values.health.periodSeconds }}

          livenessProbe:
            httpGet:
              path: {{ .Values.health.path }}
              port: http
            initialDelaySeconds: {{ .Values.health.initialDelaySeconds }}
            periodSeconds: {{ .Values.health.periodSeconds }}