{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "platform-application.serviceAccountName" . }}
  labels:
    {{- include "platform-application.labels" . | nindent 4 }}
{{- end }}