name: Promote to Production

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Image SHA to promote"
        required: true
        type: string

permissions:
  contents: write

jobs:
  promote:
    name: Promote Image to Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Update production image
        env:
          IMAGE_TAG: ${{ inputs.image_tag }}
        run: |
          sed -i \
            "s/tag: \"[^\"]*\"/tag: \"${IMAGE_TAG}\"/" \
            gitops/applications/demo-app/values-prod.yaml

      - name: Commit promotion
        env:
          IMAGE_TAG: ${{ inputs.image_tag }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add gitops/applications/demo-app/values-prod.yaml

          git diff --cached --quiet && exit 0

          git commit -m "chore: promote demo-service ${IMAGE_TAG} to production"
          git push origin main